#define leftFrontPort 12
#define leftBackPort 20
#define rightFrontPort 18
#define rightBackPort 19
#define catapultPort 11
#define elevLeftPort 2
#define elevRightPort 10
#define clawPort 9
#define rotationPort 1
#define lightSensorPort 'A'